### ISSUE TITLE
Buttons & social links often show the wrong text/icon color

### ISSUE THREAD

**Issue by kjellr** [WordPress/pattern-directory#235] opened 2021-06-28 16:57 UTC
Buttons & social links often show the wrong text/icon color in the pattern preview. 

## Examples: 

https://wordpress.org/patterns/pattern/introduction-with-image-on-the-left/
https://wordpress.org/patterns/pattern/contact-and-social-links/

Editor|Frontend Preview
---|---
<img width="1105" alt="Screen Shot 2021-06-21 at 8 17 17 AM" src="https://user-images.githubusercontent.com/1202812/122760514-3525c980-d269-11eb-8e4d-bd3272a7ba7a.png">|<img width="1012" alt="Screen Shot 2021-06-21 at 8 17 07 AM" src="https://user-images.githubusercontent.com/1202812/122760518-3656f680-d269-11eb-9c68-7e331a341bc6.png">

Editor|Frontend Preview
---|---
<img width="1105" alt="Screen Shot 2021-06-21 at 8 17 35 AM" src="https://user-images.githubusercontent.com/1202812/122760532-3bb44100-d269-11eb-8a6d-dde5a4bed497.png">|<img width="1020" alt="Screen Shot 2021-06-21 at 8 16 11 AM" src="https://user-images.githubusercontent.com/1202812/122760544-3e169b00-d269-11eb-9129-7f441b46f8a2.png">

**Comment by coreymckrill** [comment] 2021-07-14 20:47
From https://github.com/WordPress/pattern-directory/pull/266#issuecomment-874811398

> I'm pretty sure that's a gutenberg bug with custom link colors, but haven't tracked it down yet.

@ryelle is [this](https://github.com/WordPress/gutenberg/issues/31990) the issue you were thinking of?

**Comment by ryelle** [comment] 2021-07-14 21:53
I don't think that's exactly it, I'll see if I can replicate outside of the preview iframe. The issue I see here is this `important` style is overriding the links in the icon, even though the icons have colors set locally. The output HTML looks like this:

```html
<li style="color: #FFFFFF; background-color: #000000; " class="wp-social-link wp-social-link-twitter wp-block-social-link">
  <a href="https://twitter.com" aria-label="Twitter: https://twitter.com" class="wp-block-social-link-anchor"> <...svg...></a>
</li>
...
<style>.wp-elements-60ef5bd1316b8 a{color: #000000 !important;}</style>
```

**Comment by ryelle** [comment] 2021-07-14 22:34
I was able to reproduce it outside of the pattern directory, so I've made an issue in Gutenberg for it: https://github.com/WordPress/gutenberg/issues/33437.

Closing this issue for now, although once it's fixed in GB we might need to update these patterns.

**Closed as completed by ryelle** 2021-07-14 22:34 UTC
Labels: [Type] Bug, [Component] Pattern Creator, [Component] Theme
