### ISSUE TITLE
Two buttons pattern block validation error

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/pattern-directory#245] opened 2021-06-30 05:38 UTC
**Describe the bug**
The "Two buttons" pattern triggers a validation error with 5.8 RC1. It looks like the pattern is using old markup - WordPress/gutenberg#21923.

**To Reproduce**
1. Update to WP 5.8 RC1
2. Create or edit a post.
3. See validation errors in the console.

**Expected behavior**
Core patterns shouldn't trigger validation errors.

**Screenshots**
![CleanShot 2021-06-30 at 09 37 14](https://user-images.githubusercontent.com/240569/123907343-d0642080-d986-11eb-911f-dc24662c7894.png)

**Comment by jasmussen** [comment] 2021-06-30 07:31
I'm also seeing this one causing a consistent test failure in this unrelated PR: https://github.com/WordPress/gutenberg/pull/33062

<img width="1913" alt="Screenshot 2021-06-30 at 09 31 17" src="https://user-images.githubusercontent.com/1204802/123920161-f210d800-d985-11eb-8f7c-2d4be27b9610.png">

**Comment by kjellr** [comment] 2021-06-30 12:58
@ryelle as per https://github.com/WordPress/gutenberg/pull/28800, this one is getting pulled in via the API now, right? 

I double checked the markup and it's not throwing any errors in the editor itself. I even fully re-created it to be sure. 🤷‍♂️ I did notice that [it's marked as "unlisted" here in the pattern directory](https://wordpress.org/patterns/?post_type=wporg-pattern&p=5), and I'm not sure why that is.

**Comment by Mamaduka** [comment] 2021-06-30 13:11
@kjellr I think that's a temp solution to avoid failing e2e tests see - https://wordpress.slack.com/archives/C02QB2JS7/p1625051015138400?thread_ts=1625031663.134000&cid=C02QB2JS7. 

Also, @ntsekouras might have updated the pattern.

**Comment by ntsekouras** [comment] 2021-06-30 13:22
>@kjellr I think that's a temp solution to avoid failing e2e tests see -

Exactly. For now this is why it stopped failing. I'm back and forth with different kind of failures today and haven't pinpointed the root cause for this 😄

**Comment by ntsekouras** [comment] 2021-07-01 05:12
This issue can be closed now that the PR was merged. I just realized it was an issue for the directory and not GB 😄

**Closed as completed** 2021-07-01 05:37 UTC
