### ISSUE TITLE
Creator: Inspector cannot be opened again after closing

### ISSUE THREAD

**Issue by IvanZhuck** [WordPress/pattern-directory#606] opened 2023-09-13 04:23 UTC
Hi there! Found a using case which looks like a bug.

**Describe the bug**

The top right screen corner panel disappearing after switching preview mode in the pattern editor. 

**To Reproduce**

Step 1: Go to https://wordpress.org/patterns/new-pattern/
Step 2: Click to the preview mode icon on the top right screen corner and switch the preview mode to mobile
Step 3: Click to the "Type / to choose a block" in the content editing area. It will trigger disappearing the top right screen corner panel. 
Step 4: Click to any place in the content area outside content blocks. The top right screen corner panel won't appear again so you will not be able to save you changes.

**Screenshots**

https://github.com/WordPress/pattern-directory/assets/9550657/6c03e907-18cd-4a57-a4b2-f5bb09d3dab8

![Screenshot from 2023-09-13 13-59-06](https://github.com/WordPress/pattern-directory/assets/9550657/0f2300c9-6980-4baa-b38a-6c7198214da0)

**Comment by richtabor** [comment] 2023-10-20 14:53
I've found this to be funky all around. You can't open/close it without clicking first on the canvas between. May be related.

https://github.com/WordPress/pattern-directory/assets/1813435/e2179fac-106a-446c-a87d-7471bd80eefc

**Comment by ryelle** [comment] 2024-12-11 21:21
Duplicate of #561.

**Closed as not planned by ryelle** 2024-12-11 21:21 UTC
Labels: [Component] Pattern Creator
