### ISSUE TITLE
"Draft" and "Pending" preview not shown

### ISSUE THREAD

**Issue by webmandesign** [WordPress/pattern-directory#562] opened 2023-03-04 22:04 UTC
**Describe the bug**
When saving a pattern as a draft or pattern is awaiting a review, the preview is empty. I think the preview worked well in the past even for "Draft" and "Pending" patterns.

**Expected behavior**
No matter the pattern status, it should be shown in preview for the pattern author.

**Screenshots**
Note the empty previews in the screenshot:

![](https://easycaptures.com/fs/uploaded/1562/9599046860.jpg)

**Comment by ryelle** [comment] 2023-03-05 01:41
This is a duplicate of https://github.com/WordPress/pattern-directory/issues/543, though it seems like they're just white screens instead of a 404 page now. Still, I'm going to close this issue and you can follow the other issue for the fix. Thanks!

**Closed as completed by ryelle** 2023-03-05 01:41 UTC

**Comment by webmandesign** [comment] 2023-03-05 15:11
Sure, sorry for a duplicate ticket.
